src/main/java/org/synergym/backendapi/entity/AnalysisHistory.java
src/main/java/org/synergym/backendapi/entity/Category.java
src/main/java/org/synergym/backendapi/entity/Comment.java
src/main/java/org/synergym/backendapi/entity/ExerciseLog.java
src/main/java/org/synergym/backendapi/entity/Post.java
src/main/java/org/synergym/backendapi/entity/Routine.java
src/main/java/org/synergym/backendapi/entity/RoutineExercise.java
src/main/java/org/synergym/backendapi/entity/User.java

ex)
public void updateName (String newName) { this.name = newName; }
형식으로 작성

feat: add update methods to Entity

---

src/main/java/org/synergym/backendapi/dto/RoutineDTO.java
src/main/java/org/synergym/backendapi/dto/RoutineExerciseDTO.java
src/main/java/org/synergym/backendapi/repository/RoutineExerciseRepository.java
src/main/java/org/synergym/backendapi/repository/RoutineRepository.java
src/main/java/org/synergym/backendapi/service/RoutineExerciseService.java
src/main/java/org/synergym/backendapi/service/RoutineExerciseServiceImpl.java
src/main/java/org/synergym/backendapi/service/RoutineService.java
src/main/java/org/synergym/backendapi/service/RoutineServiceImpl.java

Routine, RoutineExercise
- DTO
- Service
- ServiceImpl

feat(Routine, RoutineExercise): Adding DTOs and Services

---

src/main/java/org/synergym/backendapi/dto/AnalysisHistoryDTO.java
src/main/java/org/synergym/backendapi/repository/AnalysisHistoryRepository.java
src/main/java/org/synergym/backendapi/service/AnalysisHistoryService.java
src/main/java/org/synergym/backendapi/service/AnalysisHistoryServiceImpl.java
src/test/java/org/synergym/backendapi/AnalysisHistoryServiceTest.java

AnalysisHistory
- DTO
- Service
- ServiceImpl
- Test

feat: feat(AnalysisHistory): Adding DTOs and Services, Test code

---

src/main/java/org/synergym/backendapi/controller/ExerciseController.java
src/main/java/org/synergym/backendapi/dto/ExerciseDTO.java
src/main/java/org/synergym/backendapi/dto/ExerciseLikeDTO.java
src/main/java/org/synergym/backendapi/dto/ExerciseLogDTO.java
src/main/java/org/synergym/backendapi/entity/Exercise.java
src/main/java/org/synergym/backendapi/entity/ExerciseLike.java
src/main/java/org/synergym/backendapi/entity/ExerciseLog.java
src/main/java/org/synergym/backendapi/service/ExerciseLikeService.java
src/main/java/org/synergym/backendapi/service/ExerciseLikeServiceImpl.java
src/main/java/org/synergym/backendapi/service/ExerciseLogService.java
src/main/java/org/synergym/backendapi/service/ExerciseLogServiceImpl.java
src/main/java/org/synergym/backendapi/service/ExerciseService.java
src/main/java/org/synergym/backendapi/service/ExerciseServiceImpl.java
src/main/java/org/synergym/backendapi/util/ExerciseJsonImporter.java
src/main/resources/naver_exercise_cleaned.json
src/test/java/org/synergym/backendapi/ExerciseJsonImportTest.java
src/test/java/org/synergym/backendapi/ExerciseLikeServiceTest.java
src/test/java/org/synergym/backendapi/ExerciseLogServiceTest.java
src/test/java/org/synergym/backendapi/ExerciseRepositoryTest.java
src/test/java/org/synergym/backendapi/ExerciseServiceTest.java

- DTO
- Service
- ServiceImpl
- Test

feat: feat(Exercise, ExerciseLike, ExerciseLog): Adding DTOs and Services, Test code

---

src/main/java/org/synergym/backendapi/dto/CategoryDTO.java
src/main/java/org/synergym/backendapi/exception/ErrorCode.java
src/main/java/org/synergym/backendapi/repository/CategoryRepository.java
src/main/java/org/synergym/backendapi/service/CategoryService.java
src/main/java/org/synergym/backendapi/service/CategoryServiceImpl.java
src/test/java/org/synergym/backendapi/CategoryServiceTest.java
src/test/java/org/synergym/backendapi/ExerciseJsonImportTest.java

- DTO
- Service
- Test
*ExerciseJsonImportTest 주석처리

feat(Category): add DTOs, Service, Test

---

src/main/java/org/synergym/backendapi/controller/UserController.java
src/main/java/org/synergym/backendapi/dto/ChangePasswordRequest.java
src/main/java/org/synergym/backendapi/dto/FindEmailRequest.java
src/main/java/org/synergym/backendapi/dto/ResetPasswordRequest.java
src/main/java/org/synergym/backendapi/repository/UserRepository.java
src/main/java/org/synergym/backendapi/service/AuthService.java
src/main/java/org/synergym/backendapi/service/AuthServiceImpl.java
src/main/java/org/synergym/backendapi/service/UserService.java
src/main/java/org/synergym/backendapi/service/UserServiceImpl.java

- 사용자 아이디 찾기 기능 추가 (이름, 생년월일로 조회)
- 비밀번호 찾기 및 임시 비밀번호 발급/전송 로직
- 관련 Controller, Service 메서드 추가

feat: implement find ID & password functionality

---

src/main/java/org/synergym/backendapi/dto/PostDTO.java
src/main/java/org/synergym/backendapi/entity/Post.java
src/main/java/org/synergym/backendapi/exception/ErrorCode.java
src/main/java/org/synergym/backendapi/repository/PostRepository.java
src/main/java/org/synergym/backendapi/service/PostService.java
src/main/java/org/synergym/backendapi/service/PostServiceImpl.java
src/test/java/org/synergym/backendapi/PostServiceTest.java

feat(Post) : create DTO, Service, Test

---

src/main/java/org/synergym/backendapi/config/CorsConfig.java

chore(cors): add CORS configuration for cors config

---

src/main/java/org/synergym/backendapi/dto/CommentDTO.java
src/main/java/org/synergym/backendapi/exception/ErrorCode.java
src/main/java/org/synergym/backendapi/repository/CommentRepository.java
src/main/java/org/synergym/backendapi/service/CommentService.java
src/main/java/org/synergym/backendapi/service/CommentServiceImpl.java
src/test/java/org/synergym/backendapi/CommentServiceTest.java
src/test/java/org/synergym/backendapi/PostLikeServiceTest.java

- DTO
- Service
- Test
* PostLikeServiceTest도 수정

feat(Comment) : create DTO, Service, Test

---

build.gradle
src/main/java/org/synergym/backendapi/config/CloudinaryConfig.java
src/main/java/org/synergym/backendapi/config/CloudinaryProperties.java
src/main/java/org/synergym/backendapi/controller/CloudinaryController.java
src/main/java/org/synergym/backendapi/service/CloudinaryService.java

- service
- controller
- config
- properties
- edit build.gradle

feat(cloudinary): create service, controller, config, properties & edit build

---

src/main/java/org/synergym/backendapi/dto/FindEmailRequest.java
src/main/java/org/synergym/backendapi/service/AuthServiceImpl.java
src/main/resources/application.yml

- @NotBlank, @NotNull 추가
- 디버깅용 log코드 추가

feat: edit find ID & password functionality

---

src/main/java/org/synergym/backendapi/controller/UserController.java
src/main/java/org/synergym/backendapi/dto/RoutineDTO.java
src/main/java/org/synergym/backendapi/repository/UserRepository.java
src/main/java/org/synergym/backendapi/service/RoutineService.java
src/main/java/org/synergym/backendapi/service/UserService.java
src/main/java/org/synergym/backendapi/service/UserServiceImpl.java

- 사용자 마이페이지용 프로필 사진 조회 API 추가 및 기존 로직 개선
- 사용자 사진 URL 반환을 위한 DTO 수정
- UserService 및 UserController에 프로필 이미지 관련 메서드 구현

feat: add and update user profile image retrieval API

---

src/main/java/org/synergym/backendapi/entity/User.java
src/main/java/org/synergym/backendapi/service/UserServiceImpl.java

- 사용자 정보 수정(UserService) 로직 추가

feat: update user info edit service logic

---

src/main/java/org/synergym/backendapi/dto/RoutineExerciseDTO.java
src/main/java/org/synergym/backendapi/entity/Routine.java
src/main/java/org/synergym/backendapi/entity/RoutineExercise.java
src/main/java/org/synergym/backendapi/service/RoutineServiceImpl.java

- 루틴 추가, 루틴의 운동 추가 수정을 위한 dto, entity, service코드 수정

feat: edit create, update Service to integrate with API

---

src/main/java/org/synergym/backendapi/controller/PostCounterController.java
src/main/java/org/synergym/backendapi/dto/PostCounterDTO.java
src/main/java/org/synergym/backendapi/dto/PostDTO.java
src/main/java/org/synergym/backendapi/entity/Post.java
src/main/java/org/synergym/backendapi/entity/PostCounter.java
src/main/java/org/synergym/backendapi/repository/PostCounterRepository.java
src/main/java/org/synergym/backendapi/repository/PostRepository.java
src/main/java/org/synergym/backendapi/service/CommentServiceImpl.java
src/main/java/org/synergym/backendapi/service/PostCounterService.java
src/main/java/org/synergym/backendapi/service/PostCounterServiceImpl.java
src/main/java/org/synergym/backendapi/service/PostLikeServiceImpl.java
src/main/java/org/synergym/backendapi/service/PostService.java
src/main/java/org/synergym/backendapi/service/PostServiceImpl.java

- Create PostCounter entity for like/comment/view counts
- Add PostCounterService with proper transaction management
- Update Post entity to use @OneToOne relationship with PostCounter
- Fix comment count synchronization in CommentServiceImpl
- Resolve JPA mapping and database schema issues
- Add proper error handling and DTOs

feat(community) : introduce PostCounter entity to separate counter data from Post entity

---

src/main/java/org/synergym/backendapi/config/SecurityConfig.java
src/main/java/org/synergym/backendapi/controller/UserController.java
src/main/java/org/synergym/backendapi/filter/JwtAuthenticationFilter.java
src/main/java/org/synergym/backendapi/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/org/synergym/backendapi/handler/SecurityExceptionHandler.java
src/main/java/org/synergym/backendapi/provider/JwtTokenProvider.java
src/main/java/org/synergym/backendapi/service/AuthServiceImpl.java
src/main/java/org/synergym/backendapi/service/UserDetailsService.java
src/main/java/org/synergym/backendapi/service/UserDetailsServiceImpl.java
src/main/java/org/synergym/backendapi/service/oauth/CustomOAuth2User.java
src/main/java/org/synergym/backendapi/util/JwtUtil.java
src/main/java/org/synergym/backendapi/util/SecurityUtils.java
src/main/resources/application.yml

- 표준화된 토큰 생성 및 검증을 위해 JwtTokenProvider 추가
- 요청 인증을 위한 JwtAuthenticationFilter 생성
- 사용자 세부 정보 서비스 구현
- SecurityExceptionHandler 추가
- 액세스 제어 SecurityConfig 업데이트 (ADMIN, MEMBER)
- OAuth2 인증 성공 핸들러 수정

feat: Implement JWT-based authentication and authorization system

---

build.gradle
src/main/java/org/synergym/backendapi/BackendApiApplication.java
src/main/java/org/synergym/backendapi/config/SecurityConfig.java
src/main/java/org/synergym/backendapi/service/EmailService.java
src/main/java/org/synergym/backendapi/service/UserServiceImpl.java
src/main/resources/templates/emails/forced-withdrawal.html

강제탈퇴 시 이메일 알림 기능 구현
- Thymeleaf 템플릿 엔진을 이용한 HTML 이메일 발송 기능 추가
- 관리자가 사용자를 강제탈퇴 시킬 때 자동으로 안내 이메일 발송
- 이메일 템플릿에 닉네임과 탈퇴 사유를 동적으로 표시
주요 변경사항:
- build.gradle: spring-boot-starter-thymeleaf 의존성 추가
- BackendApiApplication.java: @EnableAsync 어노테이션 추가
- SecurityConfig.java: CORS 설정 개선
- EmailService.java: HTML 이메일 발송 메서드 추가 (비동기 처리)
- UserServiceImpl.java: 강제탈퇴 시 이메일 발송 로직 통합
- forced-withdrawal.html: 강제탈퇴 안내 이메일 템플릿 생성"

feat: 강제탈퇴 시 이메일 알림 기능 구현

---

src/main/java/org/synergym/backendapi/controller/AdminController.java
src/main/java/org/synergym/backendapi/dto/UserSignupStatsResponse.java
src/main/java/org/synergym/backendapi/service/AdminService.java
src/main/java/org/synergym/backendapi/service/AdminServiceImpl.java

- Add /api/admin/user-signup-stats endpoint with year parameter
- Implement getUserSignupStats() in AdminService with Java-based aggregation
- Integrate real signup statistics with frontend MemberStatsPage charts

feat : Add user signup statistics API and integrate with frontend charts

---

src/main/java/org/synergym/backendapi/controller/ChatbotController.java
src/main/java/org/synergym/backendapi/dto/ChatMessageDTO.java
src/main/java/org/synergym/backendapi/dto/ChatRequestDTO.java
src/main/java/org/synergym/backendapi/service/ChatbotRedisService.java

- Add ChatbotController
- Add ChatbotRedisService
- Add DTO classes
- Key features
- Independent conversation session management per user
- Automatic initial message generation for video recommendations and AI consultations
- Fast conversation history storage/retrieval using Redis
- Session-based conversation history isolation to prevent cross-user data mixing
- 24-hour automatic expiration for memory efficiency

feat(redis) : implement chatbot session management and conversation history functionality

---

src/main/java/org/synergym/backendapi/controller/EmotionLogController.java
src/main/java/org/synergym/backendapi/dto/EmotionLogDTO.java
src/main/java/org/synergym/backendapi/dto/EmotionStatsDTO.java
src/main/java/org/synergym/backendapi/entity/EmotionLog.java
src/main/java/org/synergym/backendapi/entity/EmotionType.java
src/main/java/org/synergym/backendapi/entity/ExerciseLog.java
src/main/java/org/synergym/backendapi/exception/ErrorCode.java
src/main/java/org/synergym/backendapi/repository/EmotionLogRepository.java
src/main/java/org/synergym/backendapi/repository/ExerciseLogRepository.java
src/main/java/org/synergym/backendapi/service/EmotionLogService.java
src/main/java/org/synergym/backendapi/service/EmotionLogServiceImpl.java

EmotionLog 관련 Entity, DTO, Repository, Service, Controller 구현. 
통계 처리를 위한 전용 API 엔드포인트 추가.

feat(diary): emotional diary backend fuction implementation

---

src/main/java/org/synergym/backendapi/controller/ExerciseController.java
src/main/java/org/synergym/backendapi/dto/RecommendationPayloadDTO.java
src/main/java/org/synergym/backendapi/dto/RecommendationResponseDTO.java
src/main/java/org/synergym/backendapi/service/RecommendationGraphClient.java
src/main/java/org/synergym/backendapi/service/RecommendationWorkflowService.java

Java(Spring Boot) 백엔드와 Python(FastAPI) AI 서버 간의 연동을 통해 사용자 맞춤형 운동을 추천하는 전체 워크플로우를 구현했습니다.
✨ 주요 기능
-   **Java - 추천 API 엔드포인트 생성**:
-   `ExerciseController`에서 AI 운동 추천을 요청하는 `POST /api/exercises/recommend-exercises` 엔드포인트를 구현했습니다.
-   `Controller` → `Service` → `Client` 구조
🔩 아키텍처 및 DTO
-   **외부 서비스 통신 클라이언트 구현**:
-   Java 백엔드에 `RecommendationGraphClient`를 추가하여, `WebClient`를 통해 Python AI 서버와 비동기 HTTP 통신을 수행하도록 구현했습니다.
-   **데이터 규격(DTO) 정의**:
-   프론트엔드-백엔드-AI 서버 간의 데이터 요청/응답을 위한 `RecommendationPayloadDTO`와 `RecommendationResponseDTO`를 정의하여 명확한 데이터 계약을 수립했습니다.

feat(AI): AI exercise recommendation workflow backend implementation
